In [2]:
import numpy as np

In [17]:
np.random.seed(10)

people = np.random.randint(0, 20, (10, 5))
people

array([[ 9,  4, 15,  0, 17],
       [16, 17,  8,  9,  0],
       [10,  8,  4, 19, 16],
       [ 4, 15, 11, 11,  1],
       [ 8,  4, 14, 17, 19],
       [13,  5, 13, 19, 13],
       [12,  1,  4, 18, 13],
       [11, 10,  9, 15, 18],
       [16,  7, 11, 17, 14],
       [ 7, 11,  1,  0, 12]])

In [18]:
def norm(vect):
    v = vect**2
    n = np.sqrt(np.sum(v, axis=1))
    return n

In [21]:
norm(people)

array([24.71841419, 26.26785107, 28.23118843, 22.        , 30.43024811,
       29.88310559, 25.57342371, 29.17190429, 30.18277655, 17.74823935])

In [25]:
people = people/norm(people).reshape(-1,1)
people

array([[0.36410103, 0.16182268, 0.60683505, 0.        , 0.68774638],
       [0.60910959, 0.64717894, 0.3045548 , 0.34262414, 0.        ],
       [0.35421817, 0.28337454, 0.14168727, 0.67301453, 0.56674908],
       [0.18181818, 0.68181818, 0.5       , 0.5       , 0.04545455],
       [0.26289631, 0.13144816, 0.46006855, 0.55865466, 0.62437874],
       [0.43502841, 0.16731862, 0.43502841, 0.63581076, 0.43502841],
       [0.46923713, 0.03910309, 0.15641238, 0.7038557 , 0.50834023],
       [0.37707514, 0.34279559, 0.30851603, 0.51419338, 0.61703205],
       [0.53010365, 0.23192035, 0.36444626, 0.56323513, 0.46384069],
       [0.39440532, 0.61977979, 0.05634362, 0.        , 0.6761234 ]])

In [28]:
for i in range(len(people)):
    for j in range(len(people)):
        if i != j:
            print(f"Similarity of person_{i} with person_{j}: {np.dot(people[i], people[j])}")
    print('')

Similarity of person_0 with person_1: 0.5113201800958094
Similarity of person_0 with person_2: 0.6505880576981725
Similarity of person_0 with person_3: 0.5112125535214552
Similarity of person_0 with person_4: 0.825592048915385
Similarity of person_0 with person_5: 0.7486499445225642
Similarity of person_0 with person_6: 0.6217031546765086
Similarity of person_0 with person_7: 0.8043454480464606
Similarity of person_0 with person_8: 0.7707047774143704
Similarity of person_0 with person_9: 0.7430905152709472

Similarity of person_1 with person_0: 0.5113201800958094
Similarity of person_1 with person_2: 0.6728942846462607
Similarity of person_1 with person_3: 0.875595035770913
Similarity of person_1 with person_4: 0.5767278006312073
Similarity of person_1 with person_5: 0.7235991714410254
Similarity of person_1 with person_6: 0.5999176323672597
Similarity of person_1 with person_7: 0.7216652707147353
Similarity of person_1 with person_8: 0.7769569901397098
Similarity of person_1 with pers